spring:
  application:
    name: bbansrun

  config:
    import: classpath:application-oauth2.yml
    
jwt:
  secret: ${JWT_SECRET}
  expiration: 3600000 # 1 hour
  refresh-expiration: 604800000 # 7 days

#actuator heath check
management:
  endpoints:
    web:
      exposure:
        include: health