spring:
  config:
    activate:
      on-profile: prod

  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    open-in-view: false
    defer-datasource-initialization: true

  datasource:
    url: ${PROD_DB_URL}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    root: info

discord:
  webhook:
    error: ${DISCORD_WEBHOOK_ERROR}
    warn: ${DISCORD_WEBHOOK_WARN}
    info: ${DISCORD_WEBHOOK_INFO}
    debug: ${DISCORD_WEBHOOK_DEBUG}
